#! /bin/python3
import discord

from cog import *
from utils import *

class Configuration:
    ServerName          : str = ""

    """ Command Prefix """
    Prefix              : str = "+"

    """ Users Blacklisted """
    BlacklistedSkids    : list = []
    """ Blacklisted Tokens """
    BlacklistedTokens   : list = []
    """ Whitlisted Users """
    Whitlisted          : list = []
    """ Whitlisted Admin """
    WhitlistedAdmins    : list = []

    """ Log Channel | 1 Channel, All Logs """
    JoinChannel         : int | str = 0
    LogChannel          : int | str = 0

    LastMessage         : str = ""
    LastDeleted         : str = ""

    """ Watch VC Attacks """
    WatchVC             : bool = False
    CurrentVC           : str = ""
    CurrentRegion       : str = ""
    LastRegion          : str = ""          # Ensure watcher does not use the last region again

    LastMessage         : str = ""
    LastDeleted         : str = ""

class Insanity(discord.Client):
    OnJoin              : Cog
    OnMessage           : Cog
    OnMessagegDeleted   : Cog
    OnLeave             : Cog
    Config              : Configuration
    Servers             : dict[int, Configuration] = {}
    Cogs                : dCog
    async def on_ready(self):
        self.Config = Configuration()
        self.Config.ServerName = "Skidville"

        self.Servers = {}
        self.Servers[1441933074697949247] = self.Config

        self.Cogs = dCog()
        for cog in self.Cogs.Commands:
            if cog.NAME == "__on_message__":
                self.OnMessage = cog

        await self.change_presence(
            status = discord.Status.dnd,
            activity = discord.Streaming(name = "Insanity Bot", url = "https://insanity.bot")
        )

        print(f"[ + ] Firing up {self.user}....!")

    """
        [ On Join ]
    """
    async def on_guild_join(self, guild):
        print(f"[ + ] Join {guild.id}")

    async def on_guild_leave(self, guild):
        print(f"[ + ] Join {guild.id}")
        
    async def on_member_join(self, member):
        pass

    """
        [ On Message Delete ]
    """
    async def on_message_delete(self, message):
        pass
                
    async def on_member_remove(self, member):
        pass

    async def on_message(self, message):
        if message.author == self.user:
            return
        
        if message.guild.id != 1441933074697949247 and message.guild.id not in self.Servers:
            self.Servers[message.guild.id] = Configuration()
            self.Servers[message.guild.id].ServerName = message.guild.name

        if message.guild.id in self.Servers:
            cfg = self.Servers[message.guild.id]

        msg = DiscordUtils(self, message, Discord_Event_T.e_message)
        
        if self.OnMessage:
            if self.OnMessage.PASS_BASE:
                if (await self.OnMessage.CMD_HANDLER(self, msg)) == False:
                    return
                
            else:
                if (await self.OnMessage.CMD_HANDLER(msg)) == False:
                    return
                
        for cmd in self.Cogs.Commands:
            if cmd.NAME.startswith("__"):
                continue
            
            if f"{self.Config.Prefix}{cmd.NAME}" == msg.Cmd and cmd.ARG_COUNT == 0:
                if cmd.PASS_BASE != False and cmd.PASS_BASE != None:
                    await cmd.CMD_HANDLER(self, msg)
                else:
                    await cmd.CMD_HANDLER(msg)

                break

            if f"{self.Config.Prefix}{cmd.NAME}" == msg.Cmd:
                if cmd.ARG_COUNT > 0 and msg.Args.__len__() < cmd.ARG_COUNT:
                    if isinstance(cmd.INVALID_ARGS_ERR, discord.Embed):
                        await message.channel.send(embed = cmd.INVALID_ARGS_ERR)
                        break

                    await message.channel.send(cmd.INFO["Invalid_Arg_Err"])
                    break
                else:
                    if cmd.PASS_BASE != None:
                        await cmd.CMD_HANDLER(self, msg)
                    else:
                        await cmd.CMD_HANDLER(msg)

        print(f"{message.content}")
    
    def find_server_config(self, server_q: int | str) -> Configuration:
        for server in self.Servers:
            if isinstance(server_q, int) and server == server_q:
                return self.Servers[server]
            
            if isinstance(server_q, str) and server == self.Servers[server].ServerName:
                return self.Servers[server]
            
        return None

def get_bot_token() -> str:
    f = open("/cfg/token.cfg", "r")
    t = f.read()
    f.close()

    return t

inits = discord.Intents.all()
inits.message_content = True

print("[ + ] Initializing Insanity bot....!")
bot = Insanity(intents = inits)
print("[ + ] Running bot...!")
bot.run(get_bot_token())